default:
	@docker exec -u root -it qnx-build "Desktop/projet/🧑🏾‍💻Software engineering/📝School/my-project/build.sh"

qemu-run:
	@docker exec -u root -it qnx-build "qemu-aarch64 -L  'Desktop/projet/🧑🏾‍💻Software engineering/📝School/my-project/my-project'"
